server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # API
    location /api/ {
        proxy_pass http://sret-backend-service:8081$request_uri;
    }

    # Short URL
    location ~ ^/[A-Za-z0-9]+$ {
        proxy_pass http://sret-backend-service:8081/api/v1/link$request_uri;
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

}